In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("primary_merge.csv")
df.head()

Unnamed: 0_x                                             Actors  \
0             0  Charlize Theron, Christina Ricci, Bruce Dern, ...   
1             1  Devon Alan, Laura Harris, Zooey Deschanel, Mar...   
2             2  Halle Berry, Robert Downey Jr., Charles S. Dut...   
3             3  Sean Connery, Naseeruddin Shah, Peta Wilson, T...   
4             4  Pamela Anderson, Jenny McCarthy, Marny Eng, Ch...   

                                           Awards    BoxOffice  \
0  Won 1 Oscar. Another 29 wins & 25 nominations.  $34,187,787   
1                                   1 nomination.          NaN   
2                         3 wins & 7 nominations.  $59,537,388   
3                                 12 nominations.  $66,327,144   
4                         2 wins & 4 nominations.          NaN   

                            Country          DVD            Director  Episode  \
0                      Germany, USA  01 Jun 2004       Patty Jenkins      NaN   
1                       Canada, USA          NaN    Marcel Sarmiento      NaN   
2        USA, France, Canada, Spain  23 Mar 2004   Mathieu Kassovitz      NaN   
3  USA, Germany, Czech Republic, UK  16 Dec 2003  Stephen Norrington      NaN   
4                       USA, Canada  11 May 2004        David Zucker      NaN   

   Error                               Genre  ...  imdbRating  imdbVotes  \
0    NaN   Biography, Crime, Drama, Thriller  ...         7.3    123,001   
1    NaN                                 NaN  ...         6.6         31   
2    NaN           Horror, Mystery, Thriller  ...         5.8     99,552   
3    NaN  Action, Adventure, Fantasy, Sci-Fi  ...         5.8    156,033   
4    NaN                              Comedy  ...         5.5    126,494   

  seriesID totalSeasons Unnamed: 0_y    id  imdbid rating  \
0      NaN          NaN         3591   271  340855      3   
1      NaN          NaN         3592  3137  339882      1   
2      NaN          NaN         3593  5360  348836      3   
3      NaN          NaN         3594  2097  311429      0   
4      NaN          NaN         3595   325  306047      3   

                                               title  year  
0                                            Monster  2003  
1  It&#39;s Better to Be Wanted for Murder Than N...  2003  
2                                            Gothika  2003  
3             League of Extraordinary Gentlemen, The  2003  
4                                      Scary Movie 3  2003  

[5 rows x 38 columns]

In [19]:
df.columns

Index(['Unnamed: 0_x', 'Actors', 'Awards', 'BoxOffice', 'Country', 'DVD',
       'Director', 'Episode', 'Error', 'Genre', 'Language', 'Metascore',
       'Plot', 'Poster', 'Production', 'Rated', 'Ratings', 'Released',
       'Response', 'Runtime', 'Season', 'Title', 'Type', 'Unnamed: 0.1',
       'Website', 'Writer', 'Year', 'imdbID', 'imdbRating', 'imdbVotes',
       'seriesID', 'totalSeasons', 'Unnamed: 0_y', 'id', 'imdbid', 'rating',
       'title', 'year'],
      dtype='object')

In [20]:
del df['Unnamed: 0_x']
del df['Unnamed: 0_y']
del df['Unnamed: 0.1']
df.columns

Index(['Actors', 'Awards', 'BoxOffice', 'Country', 'DVD', 'Director',
       'Episode', 'Error', 'Genre', 'Language', 'Metascore', 'Plot', 'Poster',
       'Production', 'Rated', 'Ratings', 'Released', 'Response', 'Runtime',
       'Season', 'Title', 'Type', 'Website', 'Writer', 'Year', 'imdbID',
       'imdbRating', 'imdbVotes', 'seriesID', 'totalSeasons', 'id', 'imdbid',
       'rating', 'title', 'year'],
      dtype='object')

In [21]:
df['Type'].unique()

array(['movie', 'series', 'game', 'episode'], dtype=object)

In [22]:
df_movie = df.loc[df['Type'] == "movie", :]
df_movie['Type'].unique()

array(['movie'], dtype=object)

In [23]:
df_movie['Season'].unique()

array([nan])

In [24]:
df_movie['Episode'].unique()

array([nan])

In [25]:
df_movie['seriesID'].unique()

array([nan], dtype=object)

In [26]:
df_movie['totalSeasons'].unique()

array([nan])

In [27]:
del df_movie['Episode']
del df_movie['Error']
del df_movie['Response']
del df_movie['Season']
del df_movie['Type']
del df_movie['seriesID']
del df_movie['totalSeasons']
del df_movie['title']
del df_movie['year']
del df_movie['imdbid']
del df_movie['id']
del df_movie['year']

df_movie.head()

KeyError: 'year'

In [28]:
df_movie

Actors  \
0     Charlize Theron, Christina Ricci, Bruce Dern, ...   
1     Devon Alan, Laura Harris, Zooey Deschanel, Mar...   
2     Halle Berry, Robert Downey Jr., Charles S. Dut...   
3     Sean Connery, Naseeruddin Shah, Peta Wilson, T...   
4     Pamela Anderson, Jenny McCarthy, Marny Eng, Ch...   
5     Sylvie Testud, Kaori Tsuji, Tarô Suwa, Bison K...   
6     Eric Bana, Jennifer Connelly, Sam Elliott, Jos...   
7     Tony Saba, Lionnel Astier, Thomas Cousseau, Al...   
8     Jack Nicholson, Diane Keaton, Keanu Reeves, Fr...   
9     Hayden Christensen, Peter Sarsgaard, Chloë Sev...   
11    Angelina Jolie, Gerard Butler, Ciarán Hinds, C...   
12    Sara Downing, Amy Parks, Bailey Chase, Michael...   
13    Michael Caine, Robert Duvall, Haley Joel Osmen...   
14    Desmond Harrington, Eliza Dushku, Emmanuelle C...   
15    John Cusack, Gene Hackman, Dustin Hoffman, Rac...   
16    Tony Jaa, Petchtai Wongkamlao, Pumwaree Yodkam...   
17    Reese Witherspoon, Sally Field, Regina King, J...   
18    Mark Aisbett, Ashton Kutcher, Jon Abrahams, Ta...   
19    Eddie Murphy, Jeff Garlin, Steve Zahn, Regina ...   
20    Patrick Stewart, Hugh Jackman, Ian McKellen, H...   
21    Tommy Wiseau, Juliette Danielle, Greg Sestero,...   
22    David Hewlett, Andrew Miller, Gordon Pinsent, ...   
23    Russell Crowe, Paul Bettany, James D'Arcy, Edw...   
24    Colin Firth, Scarlett Johansson, Tom Wilkinson...   
25    Antonio Banderas, Carla Gugino, Alexa PenaVega...   
26    Eva Löbau, Daniela Holtz, Jan Neumann, Ilona S...   
27    Jackie Chan, Owen Wilson, Aaron Taylor-Johnson...   
28    Johnny Depp, Geoffrey Rush, Orlando Bloom, Kei...   
29    Sean Penn, Naomi Watts, Danny Huston, Carly Nahon   
30    Claus Nissen, Majken Algren Nielsen, Daniel He...   
...                                                 ...   
8051  Miriam Chin Wah Yeung, Louis Koo, Richard Ng, ...   
8052  Mandus Berg, Adam Dahlgren, Malin Eriksson, Al...   
8053  Kirin Kiki, Masatoshi Nagase, Kyara Uchida, Mi...   
8054  Joaquin Phoenix, Emma Stone, Joe Stapleton, Na...   
8055  Christa Théret, Féodor Atkine, Peter Hudson, T...   
8056  Ellen Page, Evan Rachel Wood, Max Minghella, C...   
8057  Dove Cameron, Cameron Boyce, Booboo Stewart, S...   
8058  Miles Teller, Michael B. Jordan, Kate Mara, Ja...   
8059  Angelababy, Dan Bakkedahl, Charlene Beck, Mich...   
8060            Ewa Placzynska, Mel Hoy, Richard Boylan   
8061  Olivia Wilde, Luke Wilson, Giovanni Ribisi, El...   
8062   Sylvia Chang, Yun-Fat Chow, Eason Chan, Wei Tang   
8063  Toni Gonzaga, Coco Martin, Freddie Webb, JM de...   
8064  Tristan Parrish Moore, Hannah Risinger, Jonath...   
8065  Faizal Abdullah, Aric Hidir Amin, Fatin Amira,...   
8066  Britt Robertson, Scott Eastwood, Alan Alda, Ja...   
8067  O'Shea Jackson Jr., Corey Hawkins, Jason Mitch...   
8068  Garrett Hedlund, Louise Bourgoin, Cletus Young...   
8069  Sanaa Lathan, Michael Ealy, Morris Chestnut, L...   
8070  Robert Pattinson, Peter Lucas, Lauren Gallaghe...   
8071  Matt Damon, Jessica Chastain, Kristen Wiig, Je...   
8072     Yû Aoi, Anne Suzuki, Shôko Aida, Sei Hiraizumi   
8073  Emily Blunt, Benicio Del Toro, Josh Brolin, Vi...   
8074  Louisa Krause, Whitney Able, Deborah Rush, Wil...   
8075  Tobey Maguire, Liev Schreiber, Michael Stuhlba...   
8076  ASAP Rocky, Blake Anderson, Bruce Beatty, De'a...   
8077  Adam Sandler, Andy Samberg, Selena Gomez, Kevi...   
8078  Kasumi Arimura, Nanami Abe, Morio Agata, Atsus...   
8079  Mae Whitman, Robbie Amell, Bella Thorne, Bianc...   
8080  Ambyr Childers, Thomas Jane, Bryan Greenberg, ...   

                                                 Awards     BoxOffice  \
0        Won 1 Oscar. Another 29 wins & 25 nominations.   $34,187,787   
1                                         1 nomination.           NaN   
2                               3 wins & 7 nominations.   $59,537,388   
3                                       12 nominations.   $66,327,144   
4                        

In [29]:
df_movie.columns

Index(['Actors', 'Awards', 'BoxOffice', 'Country', 'DVD', 'Director', 'Genre',
       'Language', 'Metascore', 'Plot', 'Poster', 'Production', 'Rated',
       'Ratings', 'Released', 'Runtime', 'Title', 'Website', 'Writer', 'Year',
       'imdbID', 'imdbRating', 'imdbVotes', 'rating'],
      dtype='object')

In [30]:
df_movie["Title"].count()


7972

In [32]:
df_movie.to_csv("official_data_set.csv")